# Generated by Django 6.1 on 2026-08-08 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_candidateprofile_employerprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidateprofile',
            old_name='fullname',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='is_varified',
            new_name='is_verified',
        ),
        migrations.RenameField(
            model_name='employerprofile',
            old_name='companyname',
            new_name='company_name',
        ),
    ]
