# Generated by Django 5.2.17 on 2026-08-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_fullname_candidateprofile_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='expected_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company_size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='domain',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='is_varified',
            field=models.BooleanField(default=False),
        ),
    ]
