# Generated by Django 5.2.17 on 2026-08-12 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_candidateprofile_education_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employerprofile',
            old_name='is_varified',
            new_name='is_verified',
        ),
    ]
