# Generated by Django 5.2.17 on 2026-08-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_is_varified_employerprofile_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
