# Generated by Django 5.2.17 on 2026-08-31 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_applicationauditlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationauditlog',
            old_name='creted_at',
            new_name='created_at',
        ),
    ]
