# Generated by Django 5.2.17 on 2026-09-08 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_adminauditlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminauditlog',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
