# Generated by Django 5.2.17 on 2026-09-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_rename_create_at_adminauditlog_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='resume_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
