# Generated by Django 5.2.17 on 2026-09-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_candidateprofile_resume_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='resume_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
