# Generated by Django 5.2.17 on 2026-09-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='is_available_for_ai_call',
            field=models.BooleanField(default=True),
        ),
    ]
