# Generated by Django 5.2.17 on 2026-09-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_aiquestion_aianswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinterviewsession',
            name='transcript',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
