# Generated by Django 5.2.17 on 2026-09-28 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_aiinterviewsession_transcript'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='accounts.aicall')),
            ],
        ),
    ]
