# Generated by Django 5.2.17 on 2026-10-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_calllog_reason_calllog_triggered_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questiom_text', models.TextField()),
                ('category', models.CharField(choices=[('INTRODUCTION', 'Introduction'), ('EXPERIENCE', 'Experience'), ('SKILLS', 'Skills'), ('AVAILABILITY', 'Availability'), ('SALARY', 'Salary')], max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
