# Generated by Django 5.2.17 on 2026-10-06 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_questiontemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobQuestionMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_order', models.PositiveBigIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_mappings', to='accounts.job')),
                ('question_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.questiontemplate')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('job', 'question_template'), name='unique_job_question_template')],
            },
        ),
    ]
