# Generated by Django 5.2.17 on 2026-10-07 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_jobquestionmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobquestionmapping',
            name='depends_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependent_questions', to='accounts.jobquestionmapping'),
        ),
        migrations.AddField(
            model_name='jobquestionmapping',
            name='trigger_answer',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
