# Generated by Django 5.2.17 on 2026-10-07 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_jobquestionmapping_depends_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiquestion',
            name='question_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_questions', to='accounts.jobquestionmapping'),
        ),
    ]
