# Generated by Django 5.2.17 on 2026-10-07 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_aiquestion_question_mapping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobquestionmapping',
            options={'ordering': ['question_order']},
        ),
        migrations.RenameField(
            model_name='questiontemplate',
            old_name='questiom_text',
            new_name='question_text',
        ),
        migrations.AlterField(
            model_name='jobquestionmapping',
            name='depends_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_questions', to='accounts.jobquestionmapping'),
        ),
        migrations.AlterField(
            model_name='questiontemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
